# Generated by Django 4.2.4 on 2023-10-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('account', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
