# Generated by Django 4.2.4 on 2024-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeapp', '0002_rename_your_name_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('account', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
